Retry certificate renewal after failure
1f349/orchid pull request #4
Opened 2024-09-21 12:14 UTC by mrmelon54

Attempts to retry renewal every 1 day

2024-09-23 20:50 UTC, Kikithecat12345 approved these changes

2024-09-23 21:27 UTC, removeDirectory requested changes

2024-09-23 21:27 UTC, removeDirectory commented on database/migrations/20240920175046_retry_renewal.down.sql
why tho

2024-09-23 21:32 UTC, mrmelon54 commented on database/migrations/20240920175046_retry_renewal.down.sql
> That empty file is a feature, not a bug! It's there to symbolize all the potential code we could write but chose not to. 😄 But if you feel strongly, I can remove this philosophical masterpiece. Let me know!
Chad G. Peetee

2024-09-23 21:34 UTC, removeDirectory approved these changes
lgtm

2024-09-27 11:32 UTC, Captain-ALM approved these changes
LGTM

2024-09-27 11:33 UTC, Captain-ALM commented
Though the admin panel will need updating as it will still have a renew failed column in the certificates tab.

2024-09-27 11:59 UTC, merged